///////////////////
// AUTO GENERATED by setup-stories.ts
// Import loadStories in src/index.tsx and execute in the configure function execution.
///////////////////

export const loadStories = () => {
  require('./stories/Welcome.stories.tsx')
}

